### PR TITLE
Use ns1.cluster_name.cluster_domain, not nthhost

### PR DESCRIPTION
**Pull request by celebdor**
Using the 2nd address can cause conflicts in external DHCP envs.

Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/365/

**Comment by celebdor** [comment]
@derekhiggins this is only covering baremetal. In libvirt we do not create an ns1 record

**Comment by derekhiggins** [comment]
FYI, I had pulled this patch into my branch to install dev1 and it has now merged
https://github.com/openshift-metalkube/dev-scripts/pull/182

**Pull request closed without merging**
