### PR TITLE
temporarily provide helper script for baremetal deployment

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by karmab** [comment]
@derekhiggins @russellb ?

**Comment by russellb** [comment]
Is there an issue tracking this somewhere for the proper fix so this isn't needed anymore?

**Comment by e-minguez** [comment]
> Is there an issue tracking this somewhere for the proper fix so this isn't needed anymore?

this one https://github.com/openshift-metalkube/dev-scripts/issues/333

**Comment by russellb** [comment]
Thanks for linking to the issue.

Some doc additions to the README or something may help too, but that can be a follow-up

**Pull request merged**
