### PR TITLE
Trivial README update to test CI

### PR DESCRIPTION
**Pull request by russellb**

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/585/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/588/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/590/

**Comment by russellb** [comment]
huzzah!

**Pull request closed without merging**
