### PR TITLE
WIP Bump RHCOS version to 47.334

### PR DESCRIPTION
**Pull request by vrutkovs**
Update RHCOS image to latest Beta 2 drop

TODO:
* [ ] Masters won't come up

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/144/

**Comment by hardys** [comment]
Is this working for other folks? For me the masters don't even boot, failing in the initrd-switch-root service, so pretty early in the boot process?

**Comment by vrutkovs** [comment]
That's odd, it works fine here, but also times out on CI - it could be due to a lack of cached image though

**Comment by derekhiggins** [comment]
> Is this working for other folks? For me the masters don't even boot, failing in the initrd-switch-root service, so pretty early in the boot process?

Ya, same problem here, lots of this this
`[    6.866057] ostree-prepare-root[1688]: ostree-prepare-root: Couldn't find specified OSTree root '/sysroot//ostree/boot.0/redhat-coreos-maipo/829c5e7d39799a36aeb0c4faea76de33b7138dff9ce6d62a69bf8d5df1961d1c/0': No such file or directory^M
`

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/238/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/313/

**Comment by vrutkovs** [comment]
Superseded by #192

**Pull request closed without merging**
