### PR TITLE
remove deploy bmo, as it's done through kni-installer

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by karmab** [comment]
@dhellmann please confirm we dont need the 08 script anymore

**Comment by dhellmann** [comment]
> @dhellmann please confirm we dont need the 08 script anymore

I would not expect the installer to launch the operator directly. I would expect it to launch the cluster-api-provider-baremetal component, and for *that* to launch the operator. @imain and @sadasu were working on different aspects of that.

**Comment by sadasu** [comment]
If the kni-installer is already launching the baremetal-operator, it is fine to remove it from dev-scripts. As @dhellmann mentioned, more changes are expected in how baremetal-operator is going to be deployed.

**Comment by hardys** [comment]
Can someone please link the kni-installer PR which added the BMO/cluster-api-provider-baremetal support?

I currently don't see it but must be missing something - can we add it to the commit message to allow other folks to easily see where the script content moved to?

+1 on moving things into kni-installer though

**Comment by russellb** [comment]
Yeah, I don't see this in kni-installer.  No changes have been made there in the last week.

Maybe you mixed this up with the `machine-api-operator` automatically running our machine actuator?  They are different components.  Nothing has automated baremetal-operator deployment yet.

**Comment by russellb** [comment]
As Doug mentioned earlier, the place this will be automated is either machine-api-operator, or via cluster-api-provider-baremetal (more likely).  That isn't done yet, so I think we can close this.

**Pull request closed without merging**
