### PR TITLE
Run mDNS server on bootstrap and masters

### PR DESCRIPTION
**Pull request by celebdor**
This new coredns-mdns service will provide the DNS resolution for the
nodes in the cluster. It is managed by a VIP that we set to the second
host address of the external subnet.

### CODE REVIEW

**Comment by celebdor** [comment]
This new PR for coredns-mdns is a revisit of PR#92 reworked to drop avahi for mdns-publisher, moving keepalived to use macvlan and having the bootstrap part on kni-installer https://github.com/openshift-metalkube/kni-installer/pull/16

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/243/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/256/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/259/

**Comment by celebdor** [comment]
It needs a change in kni-installer that will set DNS_VIP on /etc/resolv.conf using the same /etc/dhcp/dhclient trick as in this PR.

**Comment by celebdor** [comment]
Needs to be tested with https://github.com/openshift-metalkube/dev-scripts/pull/171

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/260/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/266/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/287/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/288/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/290/

**Comment by celebdor** [comment]
```+ oc --config ocp/auth/kubeconfig get nodes
NAME       STATUS   ROLES    AGE     VERSION
master-0   Ready    master   3m52s   v1.12.4+50c2f2340a
master-1   Ready    master   3m52s   v1.12.4+50c2f2340a
master-2   Ready    master   3m52s   v1.12.4+50c2f2340a
+ echo 'Cluster up, you can interact with it via oc --config ocp/auth/kubeconfig <command>'
Cluster up, you can interact with it via oc --config ocp/auth/kubeconfig <command>
[stack@kuryr-a32c-02 dev-scripts]$```

Ready for testing. It worked for both Ben and myself.

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/291/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/319/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/324/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/329/

**Pull request merged**
