### PR TITLE
Avoid patching files, use MachineConfig to deliver files to masters

### PR DESCRIPTION
**Pull request by vrutkovs**
Instead of patching machineconfigs use installer's manifest to add new files in resulting ignition manifest

See https://github.com/metalkube/kni-installer/blob/master/docs/user/customization.md#install-time-customization-for-machine-configuration

* Generate MachineConfig assets by assembling files in `assets/templates`
  Each machine config has a set of files to be placed on the machine. The script would read file from `assets/files/<path>` and create a valid yaml in `assets/generated`
* `create_cluster` function would ensure kni-installer picks up these files and applied them as additional MCO config
* on bootstrap MCO would add MachineConfig as additional set of files to put on master

This PR speeds up the install as the script no longer needs to patch MCO files on bootstrap and it can start masters sooner.

TODO:
* [x] Ensure MachineConfigs actually get rendered by MCO
  It seems to skip those now
* [x] Generate assets from plaintext files

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/152/

**Comment by vrutkovs** [comment]
Doesn't seem to work, for some reason MCO ignores these files, although they are being copied to the bootstrap node

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/157/

**Comment by markmc** [comment]
Definitely a nice step forward. Don't have any insight yet as to why it's not working though. Thanks!

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/233/

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/236/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/246/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/250/

**Comment by celebdor** [comment]
Looks good. keepalived config should be changed though due to a patch I'm close to merging. Nice work!

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/251/

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/276/

**Pull request merged**
