### PR TITLE
enable draining taint within kubevirt

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by fabiand** [comment]
@rmohr could you please review?

**Comment by rmohr** [comment]
Will require kubevirt 1.16.

**Comment by fabiand** [comment]
0.16 is suppose @rmohr

**Comment by rmohr** [comment]
Ah yes. I guess we don't want to wait for 1.16.

**Comment by fabiand** [comment]
Agreed.

**Comment by karmab** [comment]
yeah, we already deployed 0.16

**Comment by karmab** [comment]
@hardys ready for merging :)

**Pull request merged**
