### PR TITLE
Config NTP server accessible on the red hat network.

### PR DESCRIPTION
**Pull request by russellb**
Related to issue #354

### CODE REVIEW

**Comment by russellb** [comment]
still testing this ...

**Comment by russellb** [comment]
verified that this put the right config in place in my test deployment

**Comment by russellb** [comment]
Note this will break deployments not within the red hat network or on the VPN ...

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/563/

**Comment by hardys** [comment]
> Note this will break deployments not within the red hat network or on the VPN, but this is probably a net improvement, since that's probably the minority of these deployments. That's better than breaking the majority ...

Doesn't sound ideal - I assume that using an upstream NTP server in both cases won't work due to firewall rules or something?

Perhaps we could make it configurable?

**Comment by russellb** [comment]
> > Note this will break deployments not within the red hat network or on the VPN, but this is probably a net improvement, since that's probably the minority of these deployments. That's better than breaking the majority ...
> 
> Doesn't sound ideal - I assume that using an upstream NTP server in both cases won't work due to firewall rules or something?
> 
> Perhaps we could make it configurable?

Done ... this will now only use `clock.redhat.com` if resolvable.  Indeed, other NTP servers won't work on the red hat network ...

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/571/

**Comment by AsherShoshan** [comment]
Still having the 'NotReady' after 15-19 hours.

**Comment by hardys** [comment]
> Still having the 'NotReady' after 15-19 hours.

You'll have to provide more details and/or raise another issue please, others have reported success with this fix so you may be encountering some other problem.

**Comment by bengland2** [comment]
ceph time sync issues are usually because the 3 monitors aren't all using a local time server IP.  For example, clock.redhat.com is a CNAME that will DNS-resolve to multiple time servers in different parts of the US and this will  break Ceph, which has a maximum time skew allowed of 50 msec or so. 

Does metal3 allow the user to specify a timeserver FQDN?  Defaulting to some interplanetary time server  doesn't work well for this.

**Pull request merged**
