### PR TITLE
Use current rdo ironic python agent tar

### PR DESCRIPTION
**Pull request by karmab**
Signed-off-by: karmab <karimboumedhel@gmail.com>

### CODE REVIEW

**Comment by karmab** [comment]
fixes https://github.com/openshift-metalkube/dev-scripts/issues/208

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/360/

**Comment by derekhiggins** [comment]
> /lgtm - added @derekhiggins as I don't recall why we pinned this

It was changed because, some users (I think on certain hardware) were having problems with the current-tripleo image a few weeks ago. That problem is hopefully gone now but lets move to the "current-tripleo-rdo" image as this will have gone through an rdo phase1 promotion in addition the the tripleo-ci promotion.
https://images.rdoproject.org/master/rdo_trunk/current-tripleo-rdo/ironic-python-agent.tar

**Comment by derekhiggins** [comment]
Aslo tagging @dhellmann, as he had the environment where we were seeing the problems.

**Comment by karmab** [comment]
> https://images.rdoproject.org/master/rdo_trunk/current-tripleo-rdo/ironic-python-agent.tar

done

**Comment by dhellmann** [comment]
Given the time pressure for the demo, we should pick a good image and pin it, for now. We can upgrade between summit and GA, but we need to start introducing stability where we can.

**Comment by dtantsur** [comment]
Pinning to Stein will probably work well enough. Or we can figure out which image corresponds to Stein final (3.6.0).

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/363/

**Comment by hardys** [comment]
The pinned DLRN build doesn't seem to exist anymore, so that's probably not a good approach to stabilizing, lets land this and then decide if there's a stable branch we can switch to when that is released/ready.

**Comment by derekhiggins** [comment]
> Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/363/

Disregard any CI on this patch as CI has a cached image, I'll delete it once we merge

**Pull request merged**
